elk:
  image: willdurand/elk
  ports:
    - "80:80"
    - "5043:5043"
  hostname: logstash
  volumes:
    - ./tls:/etc/pki/tls
    - ./logstash:/etc/logstash
  volumes_from:
    - dataelk

dataelk:
  image: busybox
  volumes:
    - /data

client:
  build: ./client
  hostname: client01
  links:
    - elk
